/**
 * This class is generated by jOOQ
 */
package de.freese.jooql.tables.interfaces;

import java.io.Serializable;
import javax.annotation.Generated;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

/**
 * This class is generated by jOOQ.
 */
@Generated(value =
{
        "http://www.jooq.org", "jOOQ version:3.8.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings(
{
        "all", "unchecked", "rawtypes"
})
@Entity
@Table(name = "T_PERSON", schema = "PUBLIC")
public interface ITPerson extends Serializable
{
    /**
     * Load data from another generated Record/POJO implementing the common interface ITPerson
     */
    public void from(ITPerson from);

    /**
     * Getter for <code>PUBLIC.T_PERSON.MY_ID</code>.
     */
    @Id
    @Column(name = "MY_ID", unique = true, nullable = false, precision = 64)
    @NotNull
    public Long getMyId();

    /**
     * Getter for <code>PUBLIC.T_PERSON.NAME</code>.
     */
    @Column(name = "NAME", length = 25)
    @Size(max = 25)
    public String getName();

    /**
     * Getter for <code>PUBLIC.T_PERSON.VORNAME</code>.
     */
    @Column(name = "VORNAME", length = 25)
    @Size(max = 25)
    public String getVorname();

    /**
     * Copy data into another generated Record/POJO implementing the common interface ITPerson
     */
    public <E extends ITPerson> E into(E into);

    /**
     * Setter for <code>PUBLIC.T_PERSON.MY_ID</code>.
     */
    public ITPerson setMyId(Long value);

    // -------------------------------------------------------------------------
    // FROM and INTO
    // -------------------------------------------------------------------------

    /**
     * Setter for <code>PUBLIC.T_PERSON.NAME</code>.
     */
    public ITPerson setName(String value);

    /**
     * Setter for <code>PUBLIC.T_PERSON.VORNAME</code>.
     */
    public ITPerson setVorname(String value);
}
