-- HSQLDB
DROP TABLE IF EXISTS USERS CASCADE;
DROP TABLE IF EXISTS ROLES CASCADE;
DROP TABLE IF EXISTS USERS_ROLES CASCADE;
DROP TABLE IF EXISTS T_EMPLOYEE CASCADE;

-- H2
--DROP TABLE IF EXISTS USERS CASCADE;
--DROP TABLE IF EXISTS ROLES CASCADE;
--DROP TABLE IF EXISTS USERS_ROLES CASCADE;

CREATE TABLE USERS (ID INT, USERNAME VARCHAR(20) CHECK (USERNAME <> ''), PASSWORD VARCHAR(20) CHECK (PASSWORD <> ''));
ALTER TABLE USERS ADD CONSTRAINT USERS_PK PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT USERS_NAME_UNQ UNIQUE (USERNAME);

CREATE TABLE ROLES (ID INT, NAME VARCHAR(20));
ALTER TABLE ROLES ADD CONSTRAINT ROLES_PK PRIMARY KEY (ID);
ALTER TABLE ROLES ADD CONSTRAINT ROLES_NAME_UNQ UNIQUE (NAME);

CREATE TABLE USERS_ROLES (USER_ID INT, ROLE_ID INT);
ALTER TABLE USERS_ROLES ADD CONSTRAINT USERS_ROLES_UNQ UNIQUE (USER_ID, ROLE_ID);

CREATE TABLE T_EMPLOYEE(MY_ID BIGINT, NAME VARCHAR(25), VORNAME VARCHAR(25));
ALTER TABLE T_EMPLOYEE ADD CONSTRAINT EMPLOYEE_PK PRIMARY KEY (MY_ID);
ALTER TABLE T_EMPLOYEE ALTER COLUMN MY_ID SET NOT NULL;

--CREATE SEQUENCE OBJECT_SEQ AS BIGINT START WITH 1 INCREMENT BY 10;