/**
 * This class is generated by jOOQ
 */
package de.freese.jooql;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Schema;
import org.jooq.impl.CatalogImpl;

/**
 * This class is generated by jOOQ.
 */
@Generated(value =
{
        "http://www.jooq.org", "jOOQ version:3.8.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings(
{
        "all", "unchecked", "rawtypes"
})
public class DefaultCatalog extends CatalogImpl
{
    /**
     * The reference instance of <code></code>
     */
    public static final DefaultCatalog DEFAULT_CATALOG = new DefaultCatalog();

    /**
     *
     */
    private static final long serialVersionUID = 38265044;

    /**
     * The schema <code>PUBLIC</code>.
     */
    public final Public PUBLIC = Public.PUBLIC;

    /**
     * No further instances allowed
     */
    private DefaultCatalog()
    {
        super("");
    }

    /**
     * @see org.jooq.impl.CatalogImpl#getSchemas()
     */
    @Override
    public final List<Schema> getSchemas()
    {
        List result = new ArrayList();
        result.addAll(getSchemas0());

        return result;
    }

    /**
     * @return {@link List}
     */
    private final List<Schema> getSchemas0()
    {
        return Arrays.<Schema> asList(Public.PUBLIC);
    }
}
