/**
 * This class is generated by jOOQ
 */
package de.freese.jooql;

import javax.annotation.Generated;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;
import de.freese.jooql.tables.TPerson;
import de.freese.jooql.tables.records.TPersonRecord;

/**
 * A class modelling foreign key relationships between tables of the <code>PUBLIC</code> schema
 */
@Generated(value =
{
        "http://www.jooq.org", "jOOQ version:3.8.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings(
{
        "all", "unchecked", "rawtypes"
})
public class Keys
{
    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    /**
     * @author Thomas Freese
     */
    private static class UniqueKeys0 extends AbstractKeys
    {
        public static final UniqueKey<TPersonRecord> SYS_PK_10107 = createUniqueKey(TPerson.T_PERSON, "SYS_PK_10107", TPerson.T_PERSON.MY_ID);
    }

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    /**
     *
     */
    public static final UniqueKey<TPersonRecord> SYS_PK_10107 = UniqueKeys0.SYS_PK_10107;
}
