/**
 * This class is generated by jOOQ
 */
package de.freese.jooql;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.annotation.Generated;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import de.freese.jooql.tables.TPerson;

/**
 * This class is generated by jOOQ.
 */
@Generated(value =
{
        "http://www.jooq.org", "jOOQ version:3.8.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings(
{
        "all", "unchecked", "rawtypes"
})
public class Public extends SchemaImpl
{
    /**
     * The reference instance of <code>PUBLIC</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     *
     */
    private static final long serialVersionUID = -1875810279;

    /**
     * The table <code>PUBLIC.T_PERSON</code>.
     */
    public final TPerson T_PERSON = TPerson.T_PERSON;

    /**
     * No further instances allowed
     */
    private Public()
    {
        super("PUBLIC", null);
    }

    /**
     * @see org.jooq.impl.SchemaImpl#getCatalog()
     */
    @Override
    public Catalog getCatalog()
    {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    /**
     * @see org.jooq.impl.SchemaImpl#getTables()
     */
    @Override
    public final List<Table<?>> getTables()
    {
        List result = new ArrayList();
        result.addAll(getTables0());

        return result;
    }

    /**
     * @return {@link List}
     */
    private final List<Table<?>> getTables0()
    {
        return Arrays.<Table<?>> asList(TPerson.T_PERSON);
    }
}
