/**
 * This class is generated by jOOQ
 */
package de.freese.jooql;

import javax.annotation.Generated;
import de.freese.jooql.tables.TPerson;

/**
 * Convenience access to all tables in PUBLIC
 */
@Generated(value =
{
        "http://www.jooq.org", "jOOQ version:3.8.2"
}, comments = "This class is generated by jOOQ")
@SuppressWarnings(
{
        "all", "unchecked", "rawtypes"
})
public class Tables
{
    /**
     * The table <code>PUBLIC.T_PERSON</code>.
     */
    public static final TPerson T_PERSON = TPerson.T_PERSON;
}
